language: node_js
node_js:
  - 12.18.3
script:
  - "npm run test"

deploy:
  provider: heroku
  api_key:
    secure: "GuIY2vaAYBh/d29lddOxW0dfcMLAEg/smzrmNl7BXCZBFBvFX83rAjOUi3e5n64/zMnBhv/p95Jbl2j46hrMmMOgQoxYDsE+bQUEQWScsK3YTpBC/Z8t3YMdHZIdIyrmurWC3TivnG/RUBp8j6Ke/6Y112CqwZJi1Ri1/CFGxg4bbA/MLRXkB2LGT14IV4UDQFPBr68M9CM/Vn0OMhe7akMLgH0Kf+o2dSIZSGWkVNw8Gkp7KUmITR8oy/34ff9C2aygKtzxYwP1haN2VYVTcWXJf/mKtBRR+WdOH7KGWUULQJM82qxCnuEHcZLzh59KH4KvMMgXh3QIA2FhZJKa6l9XAjqEmlkPDRTCyZVTqX857JQ1vXrsI5YJvooCGLGhDNfWIQi8hrbbRhHyModXfpWqvj8Wy44Y7nQpgGwlJppD63EJ1LokwUhzFmBxF/ehfGPsmt5G2WwPmLY01IhX1qrWIR8eHfkHXp1wP7jZwe/W/CMoXPVreAbrMW5vkyAgIQ9i3moD1lgE3pomlAsiTY44/vBpMXkifjwLKLcj4HocKy+NqxPqdoljFR/mpCGRSNpyj/CTPnkI98bzD7AKbAfzKKsz4JFjbnpD5q2bP8z1l2RGZ4NSezT0hzjqwQqmw9PsJizm2hYB9v3nLG1XbkivrQQmLk4H1GB6RxLl/u8="
  app: shrouded-wave-72945
  on:
    repo: lilo2k/INFS809_SDM_project
    branch: travisci

# branches:
#   only: 
#     - travisci